Update rsync-script-remotoA

diff --git a/rsync-script-remotoA b/rsync-script-remotoA
--- a/rsync-script-remotoA
+++ b/rsync-script-remotoA
@@ -28,8 +28,8 @@ if [ ! -f $RKEY ]; then
   exit 2
 fi
 
-if ! ssh -i $RKEY $RUSER@$RMACHINE "test -x $RTARGET"; then
-  echo "El directorio remoto no existe o no tienes permisos"
+if [ ! ssh -i $RKEY $RUSER@$RMACHINE "test -x $RTARGET" ]; then
+  echo "El directorio remoto no existe o no tienes permisos de ejecucion"
   echo "Saliendo..."
   exit 2
 fi
@@ -75,7 +75,7 @@ if [ $NEWEST_BACKUP ]; then
 fi
 
 # Chequeamos si se ha realizado la rotación correctamente.
-if ! ssh -i $RKEY $RUSER@$RMACHINE "test -d $RTARGET/$BACKUP_DATE"; then
+if [ ! ssh -i $RKEY $RUSER@$RMACHINE "test -d $RTARGET/$BACKUP_DATE" ]; then
   echo "No se puede escribir en el directorio remoto asignado al backup"
   echo "Saliendo..."
   exit 2
@@ -85,27 +85,29 @@ echo "Verificando origen..."
 for source in $SOURCES; do
 	echo "Comprobando $source..."
 	if [ ! -x $source ]; then
-     echo "Error con $source!"
-     echo "El directorio no existe o no tienes permisos"
-     exit 2
-   fi
+		echo "Error con $source!"
+		echo "El directorio no existe o no tienes permisos de ejecucion"
+		exit 2
+	fi
 done
 
+#Últimos pasos antes de realizar la copia.
 echo "Origen comprobado. Iniciando rsync..."
 for source in $SOURCES; do
 
-  # Creamos los directorios en $TARGET para copiar la herarquía de los directorios.
-  if ! ssh -i $RKEY $RUSER@$RMACHINE "test -d $RTARGET/$BACKUP_DATE/$source"; then
+  # Creamos los directorios en $TARGET para copiar la herarquía de los directorios
+  if [ ! ssh -i $RKEY $RUSER@$RMACHINE "test -d $RTARGET/$BACKUP_DATE/$source" ]; then
     ssh -i $RKEY $RUSER@$RMACHINE "mkdir -p $RTARGET/$BACKUP_DATE/$source"
   fi
 
   # Creamos el fichero con los paquetes instalados en el sistema.
-  dpkg-query -f '${binary:Package}\n' -W > /usr/local/bin/package-selections
+  dpkg-query -f '${binary:Package}\n' -W > /package-selections
 
   # Realizamos el comando rsync.
-  rsync $VERBOSE -z -a --delete -e "ssh -i $RKEY" $source/ $RUSER@$RMACHINE:$RTARGET/$BACKUP_DATE/$source/
+  if [ ! ssh -i $RKEY $RUSER@$RMACHINE "test -d /backup/aznar-mensual/$BACKUP_DATE" ]; then
+    rsync $VERBOSE -a --delete -e "ssh -i $RKEY" $source/ $RUSER@$RMACHINE:$RTARGET/$BACKUP_DATE/$source/
+  fi
 
 done
 
 exit 0
-
